### ISSUE TITLE
SSL issue pulling soundcloud audio

### ISSUE THREAD

**Issue by albill** [snarfed/huffduff-video#24] opened 2017-02-17 03:45 UTC
When I try to pull an audio file from soundcloud, I'm seeing the following SSL handshake error:

huffduff-video
Fetching https://soundcloud.com/motherboard/cryptoparty-in-harlem ...

ERROR: Unable to download JSON metadata: (caused by URLError(SSLError(1, '_ssl.c:493: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))

**Comment by snarfed** [comment] 2017-02-17 13:06
thanks for reporting, and sorry for the trouble! will look.

**Comment by albill** [comment] 2017-02-17 18:30
Whatever you did has fixed the issue.

**Comment by albill** [comment] 2017-02-25 21:23
aaaaaand...it's back. :-)

Fetching https://soundcloud.com/panoply/elizabeth-kolbert-we-have-locked-in-centuries-of-climate-change ...

ERROR: Unable to download JSON metadata: (caused by URLError(SSLError(1, '_ssl.c:493: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure'),))

**Comment by albill** [comment] 2017-03-01 23:01
Isn't this just the need to update the youtube-dl script?

**Comment by snarfed** [comment] 2017-03-02 01:31
@albill often, yes! not this time, though. i tried that originally, and again just now - huffduff-video is currently on youtube_dl-2017.2.28 - and no luck either time. whatever fixed it originally, it wasn't me. :/

**Comment by snarfed** [comment] 2017-03-02 01:34
rg3/youtube-dl#12280 says this is because soundcloud requires SNI (!), and support for that is dependent on openssl version, system cert bundle, etc. will investigate more.

**Comment by snarfed** [comment] 2017-03-02 17:25
data points:
* `youtube-dl https://soundcloud.com/panoply/elizabeth-kolbert-we-have-locked-in-centuries-of-climate-change` works fine. so apache/mod_wsgi may be using a different openssl or python version than command line youtube-dl.
* `python2 -c 'import ssl; print(ssl.OPENSSL_VERSION)'` (recommended in rg3/youtube-dl#12280) complains `AttributeError: 'module' object has no attribute 'OPENSSL_VERSION'` (!)
* `openssl s_client -connect api.soundcloud.com:443 -servername api.soundcloud.com` verifies the cert ok:
    ```
    subject=/OU=Domain Control Validated/CN=*.soundcloud.com
    issuer=/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Domain Validation CA - SHA256 - G2
    ...
    Verify return code: 0 (ok)
    ```

**Comment by snarfed** [comment] 2017-03-03 07:11
```sh
$ python -V
Python 2.7.12
$ openssl version
OpenSSL 1.0.1k-fips 8 Jan 2015
```

**Comment by snarfed** [comment] 2017-03-03 15:37
interestingly, `python2` on the server runs python 2.6, not 2.7. not sure what apache's mod_wsgi is using.

```sh
$ python2 -V
Python 2.6.9

$ python2 -c 'import ssl; print(ssl.OPENSSL_VERSION)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'OPENSSL_VERSION'

$ python -V
Python 2.7.12

$ python -c 'import ssl; print(ssl.OPENSSL_VERSION)'
OpenSSL 1.0.1k-fips 8 Jan 2015
```

**Comment by snarfed** [comment] 2017-03-03 18:12
confirmed that apache's mod_wsgi is using python 2.6.9. that's the problem. :/ hopefully rebuilding it with python 2.7.12 will fix this.

**Comment by snarfed** [comment] 2017-03-04 05:49
worked! soundcloud works now. thanks for your patience @albill.

**Comment by albill** [comment] 2017-03-05 01:06
Confirmed! Thanks for the work.

**Comment by snarfed** [comment] 2017-03-06 16:48
looks like it's back again. :/

**Comment by snarfed** [comment] 2017-03-06 16:57
the fix didn't regress, we're still on Python 2.7.12 and OpenSSL 1.0.1k-fips, so something else is wrong.

we're now getting an HTTP 401 Unauthorized, as opposed to the SSLError connection failed from before. i suspect soundcloud is just blocking EC2 IP addresses, or youtube-dl's current soundcloud client id. :/

**Comment by snarfed** [comment] 2017-03-07 00:29
woo youtube-dl updated their soundcloud client id in version 2017.03.07, which fixed it! closing.

**Closed as completed by snarfed** 2017-03-07 00:29 UTC
